### ISSUE TITLE
ggsurvplot legend order doesn't respect level order of factors in survfit object

### ISSUE THREAD

**Issue by jbarnardj** [kassambara/survminer#74] opened 2016-11-17 15:44 UTC
### Expected behavior 
If levels(x) = c('B', 'A) and sf = survfit(Surv(time, event) ~ x, data=df)
then in the legend generated by ggsurvplot(sf), expect B to appear first followed by A

### Actual behavior
Order of labels in legend is alphabetical. Function surv_summary, which is called by ggsurvplot, appears to change the order to alphabetical in the code:

res$strata <- as.factor(rep(colnames(x$surv), each = nrow(x$surv)))

Reordering makes it more error prone to assign useful legend.labs and removes the ability of the user to specify legend label order.

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

**Comment by kassambara** [comment] 2016-11-17 18:47
fixed now! Thanks:-)!

**Closed** 2016-11-17 18:46 UTC

**Comment by andrebolerbarros** [comment] 2019-01-04 13:36
Currently having the same issue; can't really get the levels in the plot in the order I predefined

**Comment by teixeiradatt** [comment] 2020-12-02 02:25
@jbarnardj 
Hi! I have the same problem with ordering survival data. How did you fix that? Thanks!

**Comment by RoganGrant** [comment] 2021-01-03 21:34
Bumping as well. This appears to be an issue again in 0.4.8

**Comment by hchintalapudi** [comment] 2021-01-26 15:56
Same problem, in 0.4.8. Is it fixed yet?

**Comment by christian-rummey** [comment] 2021-09-02 11:20
It must be related to tibbles. 
converting data using as.data.frame() leaves the order of factor levels intact.

**Comment by Timmo83** [comment] 2021-09-29 04:40
I am still having this issue as well in 0.4.9 - any solutions yet?
Thanks

**Comment by Timmo83** [comment] 2021-09-29 04:52
> It must be related to tibbles. converting data using as.data.frame() leaves the order of factor levels intact.

I tried this, my initial data was already as a dataframe... The survfit object could not be coerced into a dataframe, if that's what you meant? Would appreciate any advice.

**Comment by christian-rummey** [comment] 2021-09-29 05:50
No. I only got the error when I used a tibble as input data. 
but right now I can't reproduce it

this gives me the correct order (2,1) in the legend. 

```
dt <- lung %>% 
  mutate(sex.c = ordered(sex, c(2,1))) %>% 
  as_tibble()

survfit( Surv(age, status)~sex.c, data = dt ) %>% 
  ggsurvplot()
```

**Comment by Timmo83** [comment] 2021-09-29 23:37
> No. I only got the error when I used a tibble as input data. but right now I can't reproduce it
> 
> this gives me the correct order (2,1) in the legend.
> 
> ```
> dt <- lung %>% 
>   mutate(sex.c = ordered(sex, c(2,1))) %>% 
>   as_tibble()
> 
> survfit( Surv(age, status)~sex.c, data = dt ) %>% 
>   ggsurvplot()
> ```

Lifesaver. Thanks!

**Comment by wp07** [comment] 2021-10-04 20:32
Thank you @christian-rummey! @kassambara was there a recent change that would cause these issues? Is there a better solution? @christian-rummey solution of re-ordering the factor levels is a good work-around but doesn't solve the underlying issue. Thanks all!

**Comment by MikeWLloyd** [comment] 2022-07-21 00:23
Realizing that this is closed, but another way to do this is the following: 
```
ggsurvplot(...,
legend.labs = levels(relevel(as.factor(data.d$Factor), 'Control'))
)
```

I had a case where I had levels in a factor, but wanted 'Control' first. Can be adapted as needed.
