### ISSUE TITLE
changing proportion picture to risk table

### ISSUE THREAD

**Issue by Feli-Anna** [kassambara/survminer#33] opened 2016-03-29 16:01 UTC
Hi again,

sorry for bringing up all these issues here, but since ggplot was updated, my code is pretty much messed up and it is really hard to fix it.

Before, the proportion of my plot to risk table was pretty nice. You could clearly see if curves cross or not.

![first line specific survival](https://cloud.githubusercontent.com/assets/17987328/14114496/773699b8-f5d7-11e5-8b82-6fb27f28e7c9.jpeg)

Using the same code now, I get approximately this:

![first line](https://cloud.githubusercontent.com/assets/17987328/14114625/e1c1ed28-f5d7-11e5-89ca-a6d9cee01a14.jpeg).

I have to hand in a report very soon and I plottet my curves with the pre-updated version, but I made some mistakes (which I can't fix now after the update....). 
I'd appreciate some suggestions to fix this :)

Thanks
Feli

**Comment by kassambara** [comment] 2016-03-29 16:17
Hi,

I think that you don't have the latest version of survminer installed on your computer.

1. Remove the current version:  
   
```r
remove.packages("survminer")
```

2. Install the latest version from GitHub

```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer")
```
3. Use survminer
   
```r
# Fit survival curves
require("survival")
fit <- survfit( Surv(time, status) ~ rx + adhere,
                data = colon )

# Visualize
library("survminer")
ggsurvplot(fit, pval = TRUE,
          risk.table = TRUE,
          risk.table.col = "strata",
          main = "Survival Curves",
          risk.table.height = 0.3, # Useful when you have multiple groups
)
```

You should have the following plot:

![rplot](https://cloud.githubusercontent.com/assets/3313355/14115162/261ec908-f5da-11e5-979f-99d539e2dc7a.png)

```r
devtools::session_info("survminer")
```

<pre>
Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2016-03-29                  

Packages --------------------------------------------------------------------------------------------------------------
 package      * version    date       source                               
 colorspace     1.2-6      2015-03-11 CRAN (R 3.2.0)                       
 dichromat      2.0-0      2013-01-24 CRAN (R 3.2.0)                       
 digest         0.6.9      2016-01-08 CRAN (R 3.2.3)                       
 ggplot2      * 2.1.0      2016-03-01 CRAN (R 3.2.4)                       
 gridExtra      2.2.1      2016-02-29 CRAN (R 3.2.4)                       
 gtable         0.2.0      2016-02-26 CRAN (R 3.2.3)                       
 labeling       0.3        2014-08-23 CRAN (R 3.2.0)                       
 magrittr       1.5        2014-11-22 CRAN (R 3.2.0)                       
 MASS           7.3-45     2015-11-10 CRAN (R 3.2.3)                       
 munsell        0.4.3      2016-02-13 CRAN (R 3.2.3)                       
 plyr           1.8.3      2015-06-12 CRAN (R 3.2.0)                       
 RColorBrewer   1.1-2      2014-12-07 CRAN (R 3.2.0)                       
 Rcpp           0.12.4     2016-03-26 CRAN (R 3.2.4)                       
 reshape2       1.4.1      2014-12-06 CRAN (R 3.2.0)                       
 scales         0.4.0      2016-02-26 CRAN (R 3.2.3)                       
 stringi        1.0-1      2015-10-22 CRAN (R 3.2.0)                       
 stringr        1.0.0      2015-04-30 CRAN (R 3.2.0)                       
 survival     * 2.38-3     2015-07-02 CRAN (R 3.2.3)                       
 survminer    * 0.2.0.9002 2016-03-29 Github (kassambara/survminer@3e9cb1f)
</pre>
Best regards,
AK

**Comment by Feli-Anna** [comment] 2016-03-30 19:44
I did as you said. 

Now I have this

![rplot01f](https://cloud.githubusercontent.com/assets/17987328/14155089/78836b36-f6c0-11e5-82c2-771e66f28dc1.jpeg)

Still, the proportions don't fit.....

**Comment by MarcinKosinski** [comment] 2016-04-14 16:58
@Feli-Anna  have your tried writing your image to `pdf` file? 

````{R}
require("survival")
fit <- survfit( Surv(time, status) ~ rx + adhere,
                data = colon )

# Visualize
library("survminer")
pdf("file.pdf", width = 15, height = 15)
ggsurvplot(fit, pval = TRUE,
          risk.table = TRUE,
          risk.table.col = "strata",
          main = "Survival Curves",
          risk.table.height = 0.3, # Useful when you have multiple groups
)
dev.off()
````

More over are you using `zoom` in RStudio to have better view of the plots that are not saved to `pdf` file?

**Comment by MarcinKosinski** [comment] 2016-05-23 11:57
@Feli-Anna ?

**Comment by MarcinKosinski** [comment] 2016-06-13 10:39
@kassambara it's been over 75 days since this request.
Are we closing this issue with `won't fix` or `can't reproduce` (or even `solved`)?

**Comment by MarcinKosinski** [comment] 2016-06-13 11:17
> I can't close this. No read/write rights and it's not mine issue. You are the only one who can close this.

**Closed** 2016-06-13 11:48 UTC
