### ISSUE TITLE
Wrong p-value if subset is specified in the model

### ISSUE THREAD

**Issue by jseoane** [kassambara/survminer#71] opened 2016-10-28 22:56 UTC
The surv.diff p-value is not the same that the one reported in the plot when a subset is selected in the fitted survival model (i.e. surv.fit(Surv(time,event)~feature,data=data1,subset=feature2==TRUE) )

This is caused because you are getting the information for calculate p-value from the original data object in the function .get_pvalue, without checking if a subset was selected.

**Comment by kassambara** [comment] 2016-10-29 00:25
Hi @jseoane ,

Thank you for pointing this out! The issue is now fixed.

Please install the latest version on Github and let me know if it's ok for you, so that we can close the issue.  

- Install
  
```r
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
```

- Example

```r
library("survival")
library("survminer")
fit <- survfit(Surv(time, status)~sex, subset = ph.ecog==1)
ggsurvplot(fit, risk.table = TRUE, pval = TRUE)
```

Best,
/A

**Closed** 2016-10-30 08:46 UTC
