### ISSUE TITLE
Error in f(...) : Aesthetics can not vary with a ribbon

### ISSUE THREAD

**Issue by iamstein** [kassambara/survminer#443] opened 2020-01-24 04:11 UTC
### Expected behavior 
produce plot

### Actual behavior
Error in f(...) : Aesthetics can not vary with a ribbon

### Steps to reproduce the problem
library(survival)
library(survminer)
surv = survfit(Surv(time) ~ ph.ecog, data = lung, conf.int = 0.95)
ggsurvplot(surv, lung, conf.int = TRUE)

### `session_info()`
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] survminer_0.4.6   ggpubr_0.2.3      magrittr_1.5      ggplot2_3.2.1    
[5] survival_2.44-1.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        pillar_1.4.2      compiler_3.6.1    tools_3.6.1      
 [5] zeallot_0.1.0     tibble_2.1.3      lifecycle_0.1.0   gtable_0.3.0     
 [9] nlme_3.1-140      lattice_0.20-38   pkgconfig_2.0.2   rlang_0.4.0      
[13] Matrix_1.2-17     rstudioapi_0.10   xfun_0.9          gridExtra_2.3    
[17] knitr_1.24        withr_2.1.2       dplyr_0.8.3       generics_0.0.2   
[21] vctrs_0.2.0       survMisc_0.5.5    grid_3.6.1        tidyselect_0.2.5 
[25] data.table_1.12.2 glue_1.3.1        KMsurv_0.1-5      R6_2.4.0         
[29] km.ci_0.5-2       purrr_0.3.2       tidyr_1.0.0       scales_1.0.0     
[33] backports_1.1.4   splines_3.6.1     assertthat_0.2.1  xtable_1.8-4     
[37] colorspace_1.4-1  ggsignif_0.6.0    labeling_0.3      lazyeval_0.2.2   
[41] munsell_0.5.0     broom_0.5.2       crayon_1.3.4      zoo_1.8-6  

````{R}
# please paste here the result of
devtools::session_info()
````
─ Session info ────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-01-23                  

─ Packages ────────────────────────────────────────────────────────────────
 package     * version  date       lib source        
 assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.4    2019-04-10 [1] CRAN (R 3.6.0)
 broom         0.5.2    2019-04-07 [1] CRAN (R 3.6.0)
 callr         3.3.1    2019-07-18 [1] CRAN (R 3.6.0)
 cli           1.1.0    2019-03-19 [1] CRAN (R 3.6.0)
 colorspace    1.4-1    2019-03-18 [1] CRAN (R 3.6.0)
 crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 data.table    1.12.2   2019-04-07 [1] CRAN (R 3.6.0)
 desc          1.2.0    2018-05-01 [1] CRAN (R 3.6.0)
 devtools      2.2.0    2019-09-07 [1] CRAN (R 3.6.0)
 digest        0.6.20   2019-07-04 [1] CRAN (R 3.6.0)
 dplyr         0.8.3    2019-07-04 [1] CRAN (R 3.6.0)
 DT            0.8      2019-08-07 [1] CRAN (R 3.6.0)
 ellipsis      0.2.0.1  2019-07-02 [1] CRAN (R 3.6.0)
 fs            1.3.1    2019-05-06 [1] CRAN (R 3.6.0)
 generics      0.0.2    2018-11-29 [1] CRAN (R 3.6.0)
 ggplot2     * 3.2.1    2019-08-10 [1] CRAN (R 3.6.0)
 ggpubr      * 0.2.3    2019-09-03 [1] CRAN (R 3.6.0)
 ggsignif      0.6.0    2019-08-08 [1] CRAN (R 3.6.0)
 glue          1.3.1    2019-03-12 [1] CRAN (R 3.6.0)
 gridExtra     2.3      2017-09-09 [1] CRAN (R 3.6.0)
 gtable        0.3.0    2019-03-25 [1] CRAN (R 3.6.0)
 htmltools     0.3.6    2017-04-28 [1] CRAN (R 3.6.0)
 htmlwidgets   1.3      2018-09-30 [1] CRAN (R 3.6.0)
 km.ci         0.5-2    2009-08-30 [1] CRAN (R 3.6.0)
 KMsurv        0.1-5    2012-12-03 [1] CRAN (R 3.6.0)
 knitr         1.24     2019-08-08 [1] CRAN (R 3.6.0)
 labeling      0.3      2014-08-23 [1] CRAN (R 3.6.0)
 lattice       0.20-38  2018-11-04 [1] CRAN (R 3.6.1)
 lazyeval      0.2.2    2019-03-15 [1] CRAN (R 3.6.0)
 lifecycle     0.1.0    2019-08-01 [1] CRAN (R 3.6.0)
 magrittr    * 1.5      2014-11-22 [1] CRAN (R 3.6.0)
 Matrix        1.2-17   2019-03-22 [1] CRAN (R 3.6.1)
 memoise       1.1.0    2017-04-21 [1] CRAN (R 3.6.0)
 munsell       0.5.0    2018-06-12 [1] CRAN (R 3.6.0)
 nlme          3.1-140  2019-05-12 [1] CRAN (R 3.6.1)
 pillar        1.4.2    2019-06-29 [1] CRAN (R 3.6.0)
 pkgbuild      1.0.5    2019-08-26 [1] CRAN (R 3.6.0)
 pkgconfig     2.0.2    2018-08-16 [1] CRAN (R 3.6.0)
 pkgload       1.0.2    2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits   1.0.2    2015-07-13 [1] CRAN (R 3.6.0)
 processx      3.4.1    2019-07-18 [1] CRAN (R 3.6.0)
 ps            1.3.0    2018-12-21 [1] CRAN (R 3.6.0)
 purrr         0.3.2    2019-03-15 [1] CRAN (R 3.6.0)
 R6            2.4.0    2019-02-14 [1] CRAN (R 3.6.0)
 Rcpp          1.0.3    2019-11-08 [1] CRAN (R 3.6.0)
 remotes       2.1.0    2019-06-24 [1] CRAN (R 3.6.0)
 rlang         0.4.0    2019-06-25 [1] CRAN (R 3.6.0)
 rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi    0.10     2019-03-19 [1] CRAN (R 3.6.0)
 scales        1.0.0    2018-08-09 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 survival    * 2.44-1.1 2019-04-01 [1] CRAN (R 3.6.1)
 survminer   * 0.4.6    2019-09-03 [1] CRAN (R 3.6.0)
 survMisc      0.5.5    2018-07-05 [1] CRAN (R 3.6.0)
 testthat      2.2.1    2019-07-25 [1] CRAN (R 3.6.0)
 tibble        2.1.3    2019-06-06 [1] CRAN (R 3.6.0)
 tidyr         1.0.0    2019-09-11 [1] CRAN (R 3.6.0)
 tidyselect    0.2.5    2018-10-11 [1] CRAN (R 3.6.0)
 usethis       1.5.1    2019-07-04 [1] CRAN (R 3.6.0)
 vctrs         0.2.0    2019-07-05 [1] CRAN (R 3.6.0)
 withr         2.1.2    2018-03-15 [1] CRAN (R 3.6.0)
 xfun          0.9      2019-08-21 [1] CRAN (R 3.6.0)
 xtable        1.8-4    2019-04-21 [1] CRAN (R 3.6.0)
 zeallot       0.1.0    2018-01-28 [1] CRAN (R 3.6.0)
 zoo           1.8-6    2019-05-28 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

**Comment by kassambara** [comment] 2020-01-24 06:37
You should specify time and status/event in the surv function:

```r

library(survival)
library(survminer)
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Basic survival curves
ggsurvplot(fit, data = lung)
```

**Comment by iamstein** [comment] 2020-01-24 15:32
I still get the error when including status.  The command works with sex, but not with ph.ecog.

library(survival)
library(survminer)
library(dplyr)
data = lung %>% filter(!is.na(ph.ecog))
surv = survfit(Surv(time, status) ~ ph.ecog, data, conf.int = 0.95)
ggsurvplot(surv, lung, conf.int = TRUE)

Error in f(...) : Aesthetics can not vary with a ribbon

**Comment by kassambara** [comment] 2020-01-25 11:47
There is only one sample in ph.ecog group 3 leading to NAs during confidence interval computation

``` r
suppressMessages(library(dplyr))
data(lung, package = "survival")
data = lung %>% filter(!is.na(ph.ecog))
# Number of samples per group
data %>% count(ph.ecog)
#> # A tibble: 4 x 2
#>   ph.ecog     n
#>     <dbl> <int>
#> 1       0    63
#> 2       1   113
#> 3       2    50
#> 4       3     1
```

<sup>Created on 2020-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kassambara** [comment] 2020-01-25 12:02
duplicate of #315, fixed now thanks

**Comment by iamstein** [comment] 2020-01-25 15:06
Awesome, thanks a lot!!!

**Closed** 2020-01-26 08:58 UTC

**Comment by liar666** [comment] 2024-11-14 16:54
Hi,

Problem does not seem to have been solved in all cases: I've got the exact same error when using `autoplot` on survival data (which I assume uses `ggsurvplot` behind the scene) + a theme.

```
lung2 = lung %>% filter(!is.na(ph.ecog))
surv = survfit(Surv(time, status) ~ ph.ecog, lung2, conf.int = 0.95)
autoplot(surv) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(face = "bold", colour = "#FF7A33", size = 12),
        axis.title.y = element_text(face = "bold", colour = "#FF7A33", size = 12),
        legend.title = element_text(face = "bold", size = 10))
  
```

**Comment by liar666** [comment] 2024-11-14 17:14
also, using:
```
library(survival)
library(survminer)
library(dplyr)
data = lung %>% filter(!is.na(ph.ecog))
surv = survfit(Surv(time, status) ~ ph.ecog, data, conf.int = 0.95)
ggsurvplot(surv, lung, conf.int = TRUE, gg_theme = theme_cleantable())
```
crashes, whereas:
```
library(survival)
library(survminer)
library(dplyr)
data = lung %>% filter(!is.na(ph.ecog))
surv = survfit(Surv(time, status) ~ ph.ecog, data, conf.int = 0.95)
ggsurvplot(surv, lung, conf.int = TRUE, gg_theme = theme_classic())
```
works....

So the problem seems to be in the themes and their management...
