### ISSUE TITLE
Risk table not calculating properly

### ISSUE THREAD

**Issue by pcheng84** [kassambara/survminer#37] opened 2016-05-05 19:26 UTC
fit<- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, pval = TRUE, conf.int = TRUE,
           risk.table = TRUE, risk.table.y.text.col = TRUE)
![image](https://cloud.githubusercontent.com/assets/5804099/15054483/07871e00-1308-11e6-8c78-8db4acba8d38.png)

**Comment by kassambara** [comment] 2016-05-05 19:41
This issue has been already discussed here: https://github.com/kassambara/survminer/issues/36.

**The conclusion of the previous discussion**:  the problem is not related to survminer but to the latest version of survival package (Ver 2.39-2). 

It should be fixed as soon as possible by the maintainer of survival package.

Meanwhile, you can use the survival package ver. 2.38-3, which should give the right numbering. 

Best,
AK

**Comment by pcheng84** [comment] 2016-05-06 07:24
Ah sorry. Didn’t see that last issue.

It works with the older survival package.

Thanks! Great work on this package!

Cheers,
Phil

**Comment by kassambara** [comment] 2016-05-06 07:33
Thank you for your feedback!

Have a great day!!
AK

**Closed by kassambara** 2016-05-06 07:33 UTC
